# Generated by Django 4.0.4 on 2022-04-26 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=500)),
                ('cpf', models.CharField(max_length=14)),
                ('specialty', models.CharField(choices=[('enf', 'Enfermeiro'), ('med', 'Médico'), ('psi', 'Psicólogo'), ('edf', 'Educação Física')], max_length=3)),
                ('documentnumber', models.CharField(max_length=50)),
                ('admin', models.BooleanField(default=False)),
                ('documenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profissional da Saúde',
                'verbose_name_plural': 'Profissionais da Saúde',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=500)),
                ('cpf', models.CharField(max_length=14)),
                ('health', models.ManyToManyField(to='profiles.healthprofile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-pk'],
            },
        ),
    ]
