# Generated by Django 4.0.4 on 2022-07-27 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='documenttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='documents.documenttype'),
        ),
    ]
