# Generated by Django 4.0.4 on 2022-05-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('mat', 'Matutino'), ('ves', 'Vespertino'), ('not', 'Noturno'), ('mad', 'Madrugada')], max_length=3)),
                ('activitytype', models.CharField(choices=[('ref', 'Refeição'), ('fis', 'Atividade Física'), ('gli', 'Medição de Glicemia Capilar'), ('pre', 'Medição de Pressão Arterial'), ('med', 'Uso de Medicamento')], max_length=3)),
                ('picture', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patientprofile')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-date'],
            },
        ),
    ]
