# Generated by Django 4.0.4 on 2022-07-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
